[build]
  command = "npm run build"
  publish = "public/"
  environment = { NODE_VERSION = "15.10.0", NPM_VERSION = "7.5.3" }

# [context.production]
# [context.deploy-preview]
# [context.branch-deploy]

[[redirects]]
  from = "https://collado-io.netlify.app/*"
  to = "https://www.collado.io/:splat"

  status = 301

[[plugins]]
  package = "netlify-plugin-gatsby-cache"
