[build]
  command = "npm run build"
  publish = "public/"
  environment = { NODE_VERSION = "v12.16.1" }

# [context.production]
# [context.deploy-preview]
# [context.branch-deploy]

[[redirects]]
  from = "https://collado-io.netlify.com/*"
  to = "https://www.collado.io/:splat"

  status = 301
