[build]
  environment = { NODE_VERSION = "lts/erbium" }

# [context.production]
# [context.deploy-preview]
# [context.branch-deploy]

[[redirects]]
  from = "https://collado-io.netlify.com/*"
  to = "https://www.collado.io/:splat"

  status = 301
